spring:
  application:
    name: crm-service
  profiles:
    default: dev

server:
  port: 8082
  shutdown: graceful

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized